config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :radios
  resources :genres

  resources :app_settings
  resources :remote_configs
  root to: 'radios#index'

  namespace :api do
    namespace :private do
      namespace :v1 do
        post 'auth/sign_in' => 'auth#sign_in'
        post 'auth/sign_out' => 'auth#sign_out'

        get 'genres' => 'genres#index'

        get 'radios' => 'radios#index'
        get 'search_by_name' => 'radios#search_by_name'
        get 'radios/:id' => 'radios#show'

        get 'remote_configs' => 'remote_configs#index'
      end
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_one :radio

  acts_as_api
  api_accessible :genres do |template|
    template.add :id
    template.add :name
    template.add :img
  end
end

app/controllers/api/private/v1/genres_controller.rb
class Api::Private::V1::GenresController < Api::Private::V1::BaseController
  def index
    @genres = Genre.all
    respond_to do |format|
      format.json {render_for_api :genres, json: @genres, root: :datas, meta: {status: 200, msg: "success"}}
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action {set_titles("General Settings", "Genres")}
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @sub_title = "All Genres"
    @new_link = view_context.link_to "New Genre", new_genre_path, class: "dropdown-item"
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @sub_title = "New Genre"
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
    @sub_title = "Editing Genre"
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|


      uploaded_io = params[:genre][:img]
      if uploaded_io
        file_name = SecureRandom.uuid
        @genre.img = "/uploads/genres/#{file_name}"
      end

      if @genre.save

        if uploaded_io
          upload_file("uploads/genres", file_name, uploaded_io)
        end

        format.html {
          flash[:success] = 'Genre was successfully created.'
          redirect_to @genre
        }
        format.json {render :show, status: :created, location: @genre}
      else
        format.html {render :new}
        format.json {render json: @genre.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|

      uploaded_io = params[:genre][:img]
      if uploaded_io
        file_name = SecureRandom.uuid
        @genre.img = "/uploads/genres/#{file_name}"
      end

      if @genre.update(genre_params)

        if uploaded_io
          upload_file("uploads/genres", file_name, uploaded_io)
        end

        format.html {
          flash[:success] = 'Genre was successfully updated.'
          redirect_to @genre
        }
        format.json {render :show, status: :ok, location: @genre}
      else
        format.html {render :edit}
        format.json {render json: @genre.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html {redirect_to genres_url, notice: 'Genre was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def genre_params
    params.require(:genre).permit(:name, :description, :is_active)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<% if @genre.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

    <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Name *</label>
  <div class="col-sm-6">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>
</div>

<div class="form-group row">
  <label for="img" class="col-sm-2 col-form-label">Image</label>
  <div class="col-sm-6">
    <%= f.file_field :img, class: "", placeholder: "Image" %>
  </div>
</div>

<div class="form-group row">
  <label for="description" class="col-sm-2 col-form-label">Description</label>
  <div class="col-sm-6">
    <%= f.text_area :description, class: "form-control", placeholder: "Enter description" %>
  </div>
</div>

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Active</label>
  <div class="col-sm-6">
    <%= f.check_box :is_active %>
  </div>
</div>

app/views/genres/edit.html.erb
<%= form_with(model: @genre, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/genres/index.html.erb
<table class="table table-bordered dataTable" id="genresTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Description</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= genre.img ? (link_to "<span class='fas fa-image'></span>".html_safe, "#{genre.img}", class: "btn btn-xs btn-primary") : "N/A" %></td>
      <td><%= genre.description %></td>
      <td><%= genre.is_active ? "Active" : "Inactive" %></td>
      <td>
        <%= link_to "<span class='fas fa-eye'></span>".html_safe, genre %>
        <%= link_to "<span class='fas fa-edit'></span>".html_safe, edit_genre_path(genre) %>
        <%= link_to "<span class='fas fa-trash alert-danger'></span>".html_safe, genre, method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(function () {
        $('#genresTable').DataTable({});
    });
</script>

app/views/genres/new.html.erb
<%= form_with(model: @genre, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/genres/show.html.erb
<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Name: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @genre.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Image: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @genre.img ? (link_to "<span class='fas fa-image'></span>".html_safe, "#{@genre.img}", class: "btn btn-xs btn-primary") : "N/A" %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Description: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @genre.description %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Status: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @genre.is_active == true ? "Active" : "Inactive" %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="mt-3">
  <%= link_to 'Edit', edit_genre_path(@genre), class: "btn btn-primary" %>
  <%= link_to 'Back', genres_path, class: "btn btn-dark" %>
</div>