config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :radios
  resources :genres

  resources :app_settings
  resources :remote_configs
  root to: 'radios#index'

  namespace :api do
    namespace :private do
      namespace :v1 do
        post 'auth/sign_in' => 'auth#sign_in'
        post 'auth/sign_out' => 'auth#sign_out'

        get 'genres' => 'genres#index'

        get 'radios' => 'radios#index'
        get 'search_by_name' => 'radios#search_by_name'
        get 'radios/:id' => 'radios#show'

        get 'remote_configs' => 'remote_configs#index'
      end
    end
  end
end

app/models/remote_config.rb
class RemoteConfig < ApplicationRecord
  belongs_to :app_type
  belongs_to :disc_type
  belongs_to :background_mode
  has_many :remote_config_android_uis, inverse_of: :remote_config
  has_many :android_uis, through: :remote_config_android_uis
  accepts_nested_attributes_for :android_uis
  accepts_nested_attributes_for :remote_config_android_uis, :allow_destroy => true

  acts_as_api
  api_accessible :remote_configs do |template|
    template.add :id
    template.add :background_mode_id
    template.add :ui_top_chart
    template.add :ui_genre
    template.add :ui_favorite
    template.add :ui_themes
    template.add :ui_detail_genre
    template.add :ui_player
    template.add :ui_search
    template.add :app_type_id
  end

  def ui_top_chart
    self.android_uis.find(1).grid_type_id
  end

  def ui_genre
    self.android_uis.find(2).grid_type_id
  end

  def ui_favorite
    self.android_uis.find(3).grid_type_id
  end

  def ui_themes
    self.android_uis.find(4).grid_type_id
  end

  def ui_detail_genre
    self.android_uis.find(5).grid_type_id
  end

  def ui_player
    self.disc_type_id
  end

  def ui_search
    self.android_uis.find(6).grid_type_id
  end

end

app/controllers/api/private/v1/remote_configs_controller.rb
class Api::Private::V1::RemoteConfigsController < Api::Private::V1::BaseController
  def index
    @remote_configs = RemoteConfig.all
    respond_to do |format|
      format.json {render_for_api :remote_configs, json: @remote_configs, root: :datas, meta: {status: 200, msg: "success"}}
    end
  end
end

app/controllers/remote_configs_controller.rb
class RemoteConfigsController < ApplicationController
  before_action {set_titles("General Settings", "Remote configs")}
  before_action :set_remote_config, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authenticity_token

  # GET /remote_configs
  # GET /remote_configs.json
  def index
    @sub_title = "All Remote Configs"
    @remote_configs = RemoteConfig.all
  end

  # GET /remote_configs/1
  # GET /remote_configs/1.json
  def show
  end

  # GET /remote_configs/new
  def new
    @sub_title = "New Remote Config"
    @remote_config = RemoteConfig.new
  end

  # GET /remote_configs/1/edit
  def edit
    @sub_title = "Editing Remote Config"
  end

  # POST /remote_configs
  # POST /remote_configs.json
  def create
  end

  # PATCH/PUT /remote_configs/1
  # PATCH/PUT /remote_configs/1.json
  def update
    # raise params.inspect
    respond_to do |format|
      if @remote_config.update(remote_config_params)
        params[:remote_config][:remote_config_android_uis_attributes].each do |key, value|

          id = params[:remote_config][:remote_config_android_uis_attributes][key][:android_ui_attributes][:id]
          grid_type_id = params[:remote_config][:remote_config_android_uis_attributes][key][:android_ui_attributes][:grid_type_id]

          android_ui = AndroidUi.find(id)
          android_ui.grid_type_id = grid_type_id
          android_ui.save

        end

        format.html {redirect_to @remote_config, notice: 'Remote Config was successfully updated.'}
        format.json {render :show, status: :ok, location: @remote_config}
      else
        format.html {render :edit}
        format.json {render json: @remote_config.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /remote_configs/1
  # DELETE /remote_configs/1.json
  def destroy
    @remote_config.destroy
    respond_to do |format|
      format.html {redirect_to remote_configs_url, notice: 'Remote Config was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_remote_config
    @remote_config = RemoteConfig.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def remote_config_params
    params.require(:remote_config).permit(:name)
  end
end

app/helpers/remote_configs_helper.rb
module RemoteConfigsHelper

  def render_grid_types(selected_grid_type_id = nil)
    # grid_types = GridType.where.not(id: except)
    grid_types = GridType.all

    if selected_grid_type_id
      options = {selected: selected_grid_type_id, class: "form-control"}
    else
      options = {prompt: "Select grid type", class: "form-control"}
    end
    select_tag("remote_config[grid_type_ids[]]", options_from_collection_for_select(grid_types, "id", "name"), options)
  end

  def render_player_types(selected_disc_type = nil)
    disc_types = DiscType.all

    if selected_disc_type
      options = {:selected => selected_disc_type.id}
    else
      options = {:prompt => "Select disc type"}
    end
    select("remote_config", "disc_type_id", disc_types.collect {|disc_type| [disc_type.name, disc_type.id]}, options, :class => "form-control")
  end

  def render_background_mode(selected_bg_mode_id = nil)
    bg_modes = BackgroundMode.all

    if selected_bg_mode_id
      options = {:selected => selected_bg_mode_id}
    else
      options = {:prompt => "Select background mode"}
    end
    select("remote_config", "background_mode_id", bg_modes.collect {|background_mode| [background_mode.name, background_mode.id]}, options, :class => "form-control")
  end

  def render_app_type(selected_app_type_id = nil)
    app_types = AppType.all

    if selected_app_type_id
      options = {:selected => selected_app_type_id}
    else
      options = {:prompt => "Select app type"}
    end
    select("remote_config", "app_type_id", app_types.collect {|app_type| [app_type.name, app_type.id]}, options, :class => "form-control")
  end


end

app/views/remote_configs/_form.html.erb
<% if @remote_config.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(remote_config.errors.count, "error") %> prohibited this remote_config from being saved:</h2>

    <ul>
      <% @remote_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group row">
  <label for="app_type_id" class="col-sm-2 col-form-label">App type</label>
  <div class="col-sm-6">
    <%= render_app_type(@remote_config.app_type.id) %>
  </div>
</div>

<%= f.fields_for :remote_config_android_uis do |cau| %>
  <%= cau.fields_for :android_ui, cau do |au| %>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"><%= cau.object.android_ui.name %></label>
      <div class="col-sm-6">
        <%= au.select(:grid_type_id, GridType.all.collect {|p| [p.name, p.id]}, {}, class: 'form-control') %>
      </div>
    </div>
  <% end %>
<% end %>

<!--<div class="form-group">
  <label for="name">UI top chart</label>
  <%#= render_grid_types("top_chart",GridType::MAGIC_GRID, @top_chart_grid_type_id) %>
</div>

<div class="form-group">
  <label for="name">UI genre</label>
  <%#= render_grid_types("genres",AndroidUi::GENRES, @genres_grid_type_id) %>
</div>

<div class="form-group">
  <label for="name">UI favourite</label>
  <%#= render_grid_types("favourites",GridType::MAGIC_GRID, @favourites_grid_type_id) %>
</div>

<div class="form-group">
  <label for="name">UI themes</label>
  <%#= render_grid_types("themes",GridType::MAGIC_GRID, @themes_grid_type_id) %>
</div>

<div class="form-group">
  <label for="name">UI details genre</label>
  <%#= render_grid_types("genre_details",GridType::MAGIC_GRID, @genre_details_grid_type_id) %>
</div>

<div class="form-group">
  <label for="name">UI search</label>
  <%#= render_grid_types("search",GridType::MAGIC_GRID, @search_grid_type_id) %>
</div>-->

<div class="form-group row">
  <label for="background_mode_id" class="col-sm-2 col-form-label">Background mode</label>
  <div class="col-sm-6">
    <%= render_background_mode(@remote_config.background_mode.id) %>
  </div>
</div>

<div class="form-group row">
  <label for="disc_type" class="col-sm-2 col-form-label">UI player</label>
  <div class="col-sm-6">
    <%= render_player_types(@remote_config.disc_type) %>
  </div>
</div>

app/views/remote_configs/edit.html.erb
<%= form_with(model: @remote_config, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/remote_configs/index.html.erb
<table class="table table-bordered dataTable" id="appConfigsTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
  <tr>
    <th>Background mode</th>
    <th>UI top chart</th>
    <th>UI genres</th>
    <th>UI favourite</th>
    <th>UI themes</th>
    <th>UI genre details</th>
    <th>UI search</th>
    <th>Background mode</th>
    <th>Disc type</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @remote_configs.each do |remote_config| %>
    <tr>
      <td><%= remote_config.app_type.name %></td>
      <% remote_config.android_uis.includes(:grid_type).each do |t| %>
        <td><%= t.grid_type.name %></td>
      <% end %>
      <td><%= remote_config.background_mode.name %></td>
      <td><%= remote_config.disc_type.name %></td>
      <td>
        <%= link_to "<span class='fas fa-eye'></span>".html_safe, remote_config %>
        <%= link_to "<span class='fas fa-edit'></span>".html_safe, edit_remote_config_path(remote_config) %>
        <%= link_to "<span class='fas fa-trash alert-danger'></span>".html_safe, remote_config, method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(function () {
        $('#appConfigsTable').DataTable({});
    })
</script>

app/views/remote_configs/new.html.erb
<%= form_with(model: @remote_config, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/remote_configs/show.html.erb
<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App type: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @remote_config.app_type.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<% @remote_config.android_uis.includes(:grid_type).each do |t| %>
  <div class="row">
    <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>UI <%= t.name %>: </b></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= t.grid_type.name %>
    </div>
  </div>
  <div class="dropdown-divider"></div>
<% end %>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Backgound mode: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @remote_config.background_mode.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Disc type: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @remote_config.disc_type.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="mt-3">
  <%= link_to 'Edit', edit_remote_config_path(@remote_config), class: "btn btn-primary" %>
  <%= link_to 'Back', remote_configs_path, class: "btn btn-dark" %>
</div>