config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :radios
  resources :genres

  resources :app_settings
  resources :remote_configs
  root to: 'radios#index'

  namespace :api do
    namespace :private do
      namespace :v1 do
        post 'auth/sign_in' => 'auth#sign_in'
        post 'auth/sign_out' => 'auth#sign_out'

        get 'genres' => 'genres#index'

        get 'radios' => 'radios#index'
        get 'search_by_name' => 'radios#search_by_name'
        get 'radios/:id' => 'radios#show'

        get 'remote_configs' => 'remote_configs#index'
      end
    end
  end
end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :copyright, presence: true
  validates :phone, presence: true
  validates :website, presence: true
  validates :facebook, presence: true
  validates :twitter, presence: true
  validates :terms_of_use, presence: true
  validates :privacy_policy, presence: true
end

app/controllers/api/private/v1/app_settings_controller.rb
class Api::Private::V1::AppSettingsController < Api::Private::V1::BaseController
  def index
    @app_settings = AppSetting.all
    respond_to do |format|
      format.json {render_for_api :app_settings, json: @app_settings, root: :datas}
    end
  end
end

app/controllers/app_settings_controller.rb
class AppSettingsController < ApplicationController
  before_action {set_titles("General Settings", "App Settings")}
  before_action :set_app_setting, only: [:show, :edit, :update, :destroy]

  # GET /app_settings
  # GET /app_settings.json
  def index
    @sub_title = "All App Settings"
    @new_link = view_context.link_to "New App Setting", new_app_setting_path, class: "dropdown-item"
    @app_settings = AppSetting.all
  end

  # GET /app_settings/1
  # GET /app_settings/1.json
  def show
  end

  # GET /app_settings/new
  def new
    @sub_title = "New App Setting"
    @app_setting = AppSetting.new
  end

  # GET /app_settings/1/edit
  def edit
    @sub_title = "Editing App Setting"
  end

  # POST /app_settings
  # POST /app_settings.json
  def create
    @app_setting = AppSetting.new(app_setting_params)

    respond_to do |format|
      if @app_setting.save
        format.html {
          flash[:success] = 'App setting was successfully created.'
          redirect_to @app_setting
        }
        format.json {render :show, status: :created, location: @app_setting}
      else
        format.html {render :new}
        format.json {render json: @app_setting.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /app_settings/1
  # PATCH/PUT /app_settings/1.json
  def update
    respond_to do |format|
      if @app_setting.update(app_setting_params)
        format.html {
          flash[:success] = 'App setting was successfully updated.'
          redirect_to @app_setting
        }
        format.json {render :show, status: :ok, location: @app_setting}
      else
        format.html {render :edit}
        format.json {render json: @app_setting.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /app_settings/1
  # DELETE /app_settings/1.json
  def destroy
    @app_setting.destroy
    respond_to do |format|
      format.html {redirect_to app_settings_url, notice: 'App setting was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_app_setting
    @app_setting = AppSetting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def app_setting_params
    params.require(:app_setting).permit(:name, :email, :copyright, :phone, :website, :facebook, :twitter, :terms_of_use, :privacy_policy)
  end
end

app/helpers/app_settings_helper.rb
module AppSettingsHelper
end

app/views/app_settings/_form.html.erb
<% if @app_setting.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@app_setting.errors.count, "error") %> prohibited this app_setting from being saved:</h2>

    <ul>
      <% @app_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Name</label>
  <div class="col-sm-6">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter app name" %>
  </div>
</div>

<div class="form-group row">
  <label for="email" class="col-sm-2 col-form-label">Email</label>
  <div class="col-sm-6">
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
</div>

<div class="form-group row">
  <label for="copyright" class="col-sm-2 col-form-label">Copyright</label>
  <div class="col-sm-6">
    <%= f.text_field :copyright, class: "form-control", placeholder: "Copyright" %>
  </div>
</div>

<div class="form-group row">
  <label for="phone" class="col-sm-2 col-form-label">Phone</label>
  <div class="col-sm-6">
    <%= f.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>
</div>

<div class="form-group row">
  <label for="website" class="col-sm-2 col-form-label">Website</label>
  <div class="col-sm-6">
    <%= f.text_field :website, class: "form-control", placeholder: "Website" %>
  </div>
</div>

<div class="form-group row">
  <label for="facebook" class="col-sm-2 col-form-label">Facebook</label>
  <div class="col-sm-6">
    <%= f.text_field :facebook, class: "form-control", placeholder: "Facebook" %>
  </div>
</div>

<div class="form-group row">
  <label for="twitter" class="col-sm-2 col-form-label">Twitter</label>
  <div class="col-sm-6">
    <%= f.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
</div>

<div class="form-group row">
  <label for="term_of_use" class="col-sm-2 col-form-label">Terms of use</label>
  <div class="col-sm-6">
    <%= f.text_area :terms_of_use, class: "form-control ckeditor", placeholder: "Terms of use" %>
  </div>
</div>

<div class="form-group row">
  <label for="privacy_policy" class="col-sm-2 col-form-label">Privacy policy</label>
  <div class="col-sm-6">
    <%= f.text_area :privacy_policy, class: "form-control ckeditor", placeholder: "Privacy policy" %>
  </div>
</div>

app/views/app_settings/edit.html.erb
<%= form_with(model: @app_setting, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/app_settings/index.html.erb
<table class="table table-bordered dataTable" id="appSettings" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
  <tr>
    <th>App name</th>
    <th>App email</th>
    <th>App copyright</th>
    <th>App phone</th>
    <th>App facebook</th>
    <th>App twitter</th>
    <th>App terms of use</th>
    <th>App privacy policy</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @app_settings.each do |app_setting| %>
    <tr>
      <td><%= app_setting.name %></td>
      <td><%= app_setting.email %></td>
      <td><%= app_setting.copyright %></td>
      <td><%= app_setting.phone %></td>
      <td><%= app_setting.facebook %></td>
      <td><%= app_setting.twitter %></td>
      <td><%= app_setting.terms_of_use %></td>
      <td><%= app_setting.privacy_policy %></td>
      <td colspan="3"><%= link_to "<span class='fas fa-eye'></span>".html_safe, app_setting %>
        <%= link_to "<span class='fas fa-edit'></span>".html_safe, edit_app_setting_path(app_setting) %>
        <%= link_to "<span class='fas fa-trash alert-danger'></span>".html_safe, app_setting, method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(function () {
        $('#appSettings').DataTable({});
    })
</script>

app/views/app_settings/new.html.erb
<%= form_with(model: @app_setting, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="actions">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/app_settings/show.html.erb
<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App name: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App email: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.email %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App copyright: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.copyright %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App phone: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.phone %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App website: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.website %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App facebook: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.facebook %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App twitter: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.twitter %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App terms of use: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.terms_of_use.html_safe %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>App privacy policy: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @app_setting.privacy_policy.html_safe %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="mt-3">
  <%= link_to 'Edit', edit_app_setting_path(@app_setting), class: "btn btn-primary" %>
  <%= link_to 'Back', app_settings_path, class: "btn btn-dark" %>
</div>