config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :radios
  resources :genres

  resources :app_settings
  resources :remote_configs
  root to: 'radios#index'

  namespace :api do
    namespace :private do
      namespace :v1 do
        post 'auth/sign_in' => 'auth#sign_in'
        post 'auth/sign_out' => 'auth#sign_out'

        get 'genres' => 'genres#index'

        get 'radios' => 'radios#index'
        get 'search_by_name' => 'radios#search_by_name'
        get 'radios/:id' => 'radios#show'

        get 'remote_configs' => 'remote_configs#index'
      end
    end
  end
end

app/models/radio.rb
class Radio < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :genre_id, presence: true
  validates :link_radio, presence: true
  validates :tags, presence: true

  belongs_to :genre

  acts_as_api

  api_accessible :radios do |template|
    template.add :id
    template.add :name
    template.add :img
    template.add :bitrate
    template.add :tags
    template.add :type_radio
    template.add :source_radio
    template.add :link_radio
    template.add :user_agent_radio
    template.add :url_facebook
    template.add :url_twitter
    template.add :url_instagram
    template.add :url_website
  end
end

app/controllers/api/private/v1/radios_controller.rb
class Api::Private::V1::RadiosController < Api::Private::V1::BaseController
  def index
    if params[:genre_id]
      @radios = Radio.where(genre_id: params[:genre_id])
    else
      @radios = Radio.all
    end

    respond_to do |format|
      format.json {render_for_api :radios, json: @radios, root: :datas, meta: {status: 200, msg: "success"}}
    end
  end

  def show
    @radio = Radio.find(params[:id])
    respond_to do |format|
      format.json {render_for_api :radios, json: @radio, root: :datas, meta: {status: 200, msg: "success"}}
    end
  end

  def search_by_name
    @radio = Radio.where("name LIKE '%#{params[:q]}%'")
    respond_to do |format|
      format.json {render_for_api :radios, json: @radio, root: :datas, meta: {status: 200, msg: "success"}}
    end
  end

end

app/controllers/radios_controller.rb
class RadiosController < ApplicationController
  before_action {set_titles("General Settings", "Radios")}
  before_action :set_radio, only: [:show, :edit, :update, :destroy]

  # GET /radios
  # GET /radios.json
  def index
    @sub_title = "All Radios"
    @new_link = view_context.link_to "New Radio", new_radio_path, class: "dropdown-item"
    @radios = Radio.all
  end

  # GET /radios/1
  # GET /radios/1.json
  def show
  end

  # GET /radios/new
  def new
    @sub_title = "New Radio"
    @radio = Radio.new
  end

  # GET /radios/1/edit
  def edit
    @sub_title = "Editing Radio"
  end

  # POST /radios
  # POST /radios.json
  def create
    @radio = Radio.new(radio_params)

    respond_to do |format|

      uploaded_io = params[:radio][:img]

      if uploaded_io
        file_name = SecureRandom.uuid
        @radio.img = "/uploads/radios/#{file_name}"
      end

      if @radio.save

        if uploaded_io
          upload_file("uploads/radios", file_name, uploaded_io)
        end

        format.html {
          flash[:success] = 'Radio was successfully  created.'
          redirect_to @radio
        }
        format.json {render :show, status: :created, location: @radio}
      else
        format.html {render :new}
        format.json {render json: @radio.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /radios/1
  # PATCH/PUT /radios/1.json
  def update
    respond_to do |format|

      uploaded_io = params[:radio][:img]
      if uploaded_io
        file_name = SecureRandom.uuid
        @radio.img = "/uploads/radios/#{file_name}"
      end

      if @radio.update(radio_params)

        if uploaded_io
          upload_file("uploads/radios", file_name, uploaded_io)
        end

        format.html {
          flash[:success] = 'Radio was successfully  updated.'
          redirect_to @radio
        }
        format.json {render :show, status: :ok, location: @radio}
      else
        format.html {render :edit}
        format.json {render json: @radio.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /radios/1
  # DELETE /radios/1.json
  def destroy
    @radio.destroy
    respond_to do |format|
      format.html {redirect_to radios_url, notice: 'Radio was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_radio
    @radio = Radio.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def radio_params
    params.require(:radio).permit(:name, :genre_id, :tags, :bitrate, :type_radio, :source_radio, :link_radio, :user_agent_radio,
                                  :url_facebook, :url_twitter, :url_instagram, :url_website, :is_featured, :is_active)
  end
end

app/helpers/radios_helper.rb
module RadiosHelper
  def render_genres(genre = nil)
    genres = Genre.all

    if genre
      options = {:selected => genre.id}
    else
      options = {:prompt => "Select genre"}
    end

    select("radio", "genre_id", genres.collect {|genre| [genre.name, genre.id]}, options, :class => "form-control")
  end
end

app/views/radios/_form.html.erb
<% if @radio.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@radio.errors.count, "error") %> prohibited this radio from being saved:</h2>

    <ul>
      <% @radio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Name *</label>
  <div class="col-sm-6">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter radio name" %>
  </div>
</div>

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Genre *</label>
  <div class="col-sm-6">
    <%= render_genres @radio.genre %>
  </div>
</div>

<div class="form-group row">
  <label for="tags" class="col-sm-2 col-form-label">Tags *</label>
  <div class="col-sm-6">
    <%= f.text_field :tags, class: "form-control", placeholder: "Tags" %>
  </div>
</div>

<div class="form-group row">
  <label for="bitrate" class="col-sm-2 col-form-label">Bitrate</label>
  <div class="col-sm-6">
    <%= f.text_field :bitrate, class: "form-control", placeholder: "Bitrate" %>
  </div>
</div>

<div class="form-group row">
  <label for="img" class="col-sm-2 col-form-label">Image</label>
  <div class="col-sm-6">
    <%= f.file_field :img, class: "", placeholder: "Image" %>
  </div>
</div>

<div class="form-group row">
  <label for="type_radio" class="col-sm-2 col-form-label">Radio type</label>
  <div class="col-sm-6">
    <%= f.text_field :type_radio, class: "form-control", placeholder: "Radio type" %>
  </div>
</div>

<div class="form-group row">
  <label for="source_radio" class="col-sm-2 col-form-label">Source</label>
  <div class="col-sm-6">
    <%= f.text_field :source_radio, class: "form-control", placeholder: "Source" %>
  </div>
</div>

<div class="form-group row">
  <label for="link_radio" class="col-sm-2 col-form-label">Stream URL *</label>
  <div class="col-sm-6">
    <%= f.text_field :link_radio, class: "form-control", placeholder: "Stream URL" %>
  </div>
</div>

<div class="form-group row">
  <label for="user_agent_radio" class="col-sm-2 col-form-label">User agent radio</label>
  <div class="col-sm-6">
    <%= f.text_field :user_agent_radio, class: "form-control", placeholder: "User agent radio" %>
  </div>
</div>

<div class="form-group row">
  <label for="url_facebook" class="col-sm-2 col-form-label">Facebook</label>
  <div class="col-sm-6">
    <%= f.text_field :url_facebook, class: "form-control", placeholder: "Facebook" %>
  </div>
</div>

<div class="form-group row">
  <label for="url_twitter" class="col-sm-2 col-form-label">Twitter</label>
  <div class="col-sm-6">
    <%= f.text_field :url_twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
</div>

<div class="form-group row">
  <label for="url_instagram" class="col-sm-2 col-form-label">Instagram</label>
  <div class="col-sm-6">
    <%= f.text_field :url_instagram, class: "form-control", placeholder: "Instagram" %>
  </div>
</div>

<div class="form-group row">
  <label for="url_website" class="col-sm-2 col-form-label">Website</label>
  <div class="col-sm-6">
    <%= f.text_field :url_website, class: "form-control", placeholder: "www.radio.com" %>
  </div>
</div>

<div class="form-group row">
  <label for="is_featured" class="col-sm-2 col-form-label">Featured</label>
  <div class="col-sm-6">
    <%= f.check_box :is_featured %>
  </div>
</div>

<div class="form-group row">
  <label for="is_active" class="col-sm-2 col-form-label">Active</label>
  <div class="col-sm-6">
    <%= f.check_box :is_active %>
  </div>
</div>

app/views/radios/edit.html.erb
<%= form_with(model: @radio, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/radios/index.html.erb
<table class="table table-bordered dataTable" id="radiosTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
  <tr>
    <th>Name</th>
    <th>Genre</th>
    <th>Tags</th>
    <th>Bitrate</th>
    <th>Image</th>
    <th>Type</th>
    <th>Source</th>
    <th>Stream URL</th>
    <th>User agent</th>
    <th>Facebook</th>
    <th>Twitter</th>
    <th>Instagram</th>
    <th>Website</th>
    <th>Featured</th>
    <th>Active</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @radios.each do |radio| %>
    <tr>
      <td><%= radio.name %></td>
      <td><%= radio.genre.name %></td>
      <td><%= radio.tags %></td>
      <td><%= radio.bitrate %></td>
      <td><%= radio.img ? (link_to "<span class='fas fa-image'></span>".html_safe, "#{radio.img}", class: "btn btn-xs btn-primary") : "N/A" %></td>
      <td><%= radio.type_radio %></td>
      <td><%= radio.source_radio %></td>
      <td><%= radio.link_radio %></td>
      <td><%= radio.user_agent_radio %></td>
      <td><%= link_to "<span class='fab fa-facebook'></span>".html_safe, radio.url_facebook, class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to "<span class='fab fa-twitter'></span>".html_safe, radio.url_twitter, class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to "<span class='fab fa-instagram'></span>".html_safe, radio.url_instagram, class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to "<span class='fas fa-globe-africa'></span>".html_safe, radio.url_website, class: "btn btn-xs btn-primary" %></td>
      <td><%= radio.is_featured ? "Yes" : "No" %></td>
      <td><%= radio.is_active ? "Yes" : "No" %></td>
      <td>
        <%= link_to "<span class='fas fa-eye'></span>".html_safe, radio %>
        <%= link_to "<span class='fas fa-edit'></span>".html_safe, edit_radio_path(radio) %>
        <%= link_to "<span class='fas fa-trash alert-danger'></span>".html_safe, radio, method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(function () {
        $("#radiosTable").DataTable({});
    })
</script>

app/views/radios/new.html.erb
<%= form_with(model: @radio, local: true) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="dropdown-divider"></div>
  <div class="mt-3">
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-6">
        <%= link_to 'Back', :back, class: "btn btn-dark" %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/radios/show.html.erb
<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b> Name: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b> Genre: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.genre.name %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Tags: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.tags %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Bitrate: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.bitrate %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Image: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.img ? (link_to "<span class='fas fa-image'></span>".html_safe, "#{@radio.img}", class: "btn btn-xs btn-primary") : "N/A" %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Type: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.type_radio %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Source: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.source_radio %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Stream URL: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.link_radio %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>User agent radio: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.user_agent_radio %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Facebook: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.url_facebook %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Twitter: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.url_twitter %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Instagram: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.url_instagram %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Website: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.url_website %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Featured: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.is_featured ? "Yes" : "No" %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="row">
  <label class="control-label col-md-2 col-sm-3 col-xs-12"><b>Active: </b></label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= @radio.is_active ? "Yes" : "No" %>
  </div>
</div>
<div class="dropdown-divider"></div>

<div class="mt-3">
  <%= link_to 'Edit', edit_radio_path(@radio), class: "btn btn-primary" %>
  <%= link_to 'Back', radios_path, class: "btn btn-dark" %>
</div>